---
driver:
  name: vagrant
  customize:
    memory: 1024
    cpus: 2
  synced_folders:
    - ["shared", "/home/vagrant/src", "create: true"]


provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: centos-7.3

suites:
  - name: default
    run_list:
      - recipe[hab_studio_environment::default]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
